import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';
import { fonts } from '../../theme/fonts';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#DFE3E8',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 24,
  },
  statsPanel: {
    padding: 20,
  },
  statsPanelInner: {
    backgroundColor: colors.statsPanelContainer,
    flexDirection: 'row',
    flexWrap: 'wrap',
    borderRadius: 15,
    padding: 15,
    width: '100%',
  },
  statCell: {
    width: '33.33%',
    alignItems: 'center',
    borderBottomWidth: 0.5,
    borderRightWidth: 0.5,
    borderColor: colors.whiteColor,
    padding: 10,
  },
  statCellNoRightBorder: {
    borderRightWidth: 0,
  },
  statCellNoBottomBorder: {
    borderBottomWidth: 0,
  },
  statIconCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 12,
  },
  statIcon: {
    width: 40,
    height: 40,
  },
  statValue: {
    marginTop: 8,
    fontSize: 18,
    fontFamily: fonts.neueHaasBold,
    fontWeight: '700',
    color: colors.textColor,
  },
  statLabel: {
    marginTop: 2,
    fontSize: 12,
    color: colors.textColor,
    textAlign: 'center',
  },
  chartSection: {
    backgroundColor: colors.whiteColor,
    padding: 16,
    minHeight: 200,
  },
  chartTabBar: {
    flexDirection: 'row',
    borderWidth: 0.5,
    borderColor: colors.greyColor,
    borderRadius: 28,
    backgroundColor: colors.whiteColor,
    overflow: 'hidden',
    marginBottom: 14,
    marginHorizontal: 20,
  },
  chartTab: {
    flex: 1,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chartTabActive: {
    backgroundColor: colors.bgColor,
  },
  chartTabText: {
    fontSize: 13,
    fontFamily: fonts.neueHaasBold,
    fontWeight: '700',
    color: colors.textColor,
    textAlign: 'center',
  },
  statisticsChartCard: {
    backgroundColor: colors.whiteColor,
    paddingVertical: 16,
    paddingHorizontal: 14,
    marginHorizontal: 10,
  },
  monthlyChartCard: {
    backgroundColor: colors.whiteColor,
    paddingVertical: 16,
    paddingHorizontal: 12,
    marginHorizontal: 10,
  },
  monthlyBarChart: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
  },
  monthlyBarColumn: {
    flex: 1,
    alignItems: 'center',
  },
  monthlyBarTrack: {
    width: 10,
    borderRadius: 5,
    backgroundColor: '#E8EAED',
    justifyContent: 'flex-end',
    overflow: 'hidden',
  },
  monthlyBarFill: {
    width: '100%',
    borderRadius: 5,
  },
  monthlyBarLabel: {
    marginTop: 8,
    fontSize: 12,
    fontFamily: fonts.neueHaasRoman,
    color: colors.lightGrey,
    fontWeight: '500',
  },
  monthlyChartDivider: {
    height: 1,
    backgroundColor: '#E5E7EB',
    marginVertical: 16,
    marginHorizontal: 4,
  },
  monthlySummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
  },
  monthlySummaryItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  monthlySummaryText: {
    marginLeft: 10,
    flex: 1,
  },
  monthlySummaryLabel: {
    fontSize: 14,
    fontFamily: fonts.neueHaasBold,
    fontWeight: '700',
    color: colors.textColor,
    marginBottom: 2,
  },
  monthlySummaryValue: {
    fontSize: 13,
    fontFamily: fonts.neueHaasRoman,
    color: colors.greyColor,
  },
  statisticsChartRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statisticsLegend: {
    flex: 1,
    marginLeft: 12,
    gap: 14,
  },
  statisticsLegendRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statisticsLegendSwatch: {
    width: 14,
    height: 14,
    borderRadius: 3,
    marginRight: 10,
  },
  statisticsLegendText: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statisticsLegendLabel: {
    fontSize: 14,
    fontFamily: fonts.neueHaasRoman,
    color: colors.greyColor,
    flex: 1,
    marginRight: 8,
  },
  statisticsLegendValue: {
    fontSize: 14,
    fontFamily: fonts.neueHaasBold,
    fontWeight: '700',
    color: colors.textColor,
  },
  reviewSection: {
    backgroundColor: '#F4F5F6',
    marginTop: 8,
    paddingHorizontal: 10,
    paddingTop: 12,
    paddingBottom: 8,
    flex: 1,
  },
  reviewSectionTitle: {
    fontSize: 22,
    fontFamily: fonts.neueHaasBold,
    fontWeight: '800',
    color: colors.textColor,
    marginHorizontal: 4,
    marginBottom: 10,
  },
  reviewCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.whiteColor,
    borderRadius: 10,
    borderWidth: 0.5,
    borderColor: colors.greyColor,
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  reviewCardText: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingRight: 12,
  },
  reviewCardTitle: {
    fontSize: 15,
    fontFamily: fonts.neueHaasBold,
    fontWeight: '700',
    color: colors.textColor,
    marginBottom: 4,
  },
  reviewCardDesc: {
    fontSize: 12,
    fontFamily: fonts.neueHaasRoman,
    color: colors.greyColor,
    lineHeight: 17,
  },
  arrowRightWith: {
    width: 24,
    height: 24,
  },
  reviewCardTextContent: {
    flex: 1,
  },
});
