import { Platform, StyleSheet } from "react-native";
import { colors } from "../../theme/colors";
import { fonts } from "../../theme/fonts";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bgColor,
  },
  title: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textColor,
  },
  invoicesContainer: {
    flex: 7,
    backgroundColor: colors.whiteColor,
    flexDirection: 'row',
    gap: 10,
    borderWidth: 0.5,
    borderColor: colors.borderColor,
    padding: 5,
    marginTop: 10,
    borderRadius: 20,
  },
  invoiceItem: {
    // flex: 1,
    alignItems: 'center',
    paddingVertical: 5,
    paddingHorizontal: 10,
    justifyContent: 'center',
  },
  invoiceItemText: {
    fontSize: 14,
    fontWeight: '700',
    fontFamily: fonts.neueHaasBold,
    color: colors.textColor,
  },
  selectedInvoiceItem: {
    backgroundColor: colors.bgColor,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 20,
  },
  invoiceHeaderContainer: {
    flexDirection: 'row',
    gap: 10,
    marginHorizontal: 16,
    marginVertical: 10,
  },
  buyDateContainer: {
    flex: 3,
    marginTop: 10,
    backgroundColor: colors.whiteColor,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    flexDirection: 'row',
    borderRadius: 20,
    borderWidth: 0.5,
    borderColor: colors.borderColor,
    padding: 5,
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 96,
    gap: 12,
  },
  invoiceCard: {
    backgroundColor: colors.whiteColor,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    overflow: 'hidden',
  },
  invoiceCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 12,
    gap: 12,
  },
  invoiceCardLeft: {
    flex: 1,
    minWidth: 0,
  },
  invoiceCardMeta: {
    fontSize: 12,
    color: '#666666',
    fontFamily: fonts.neueHaasRoman,
    marginBottom: 4,
  },
  invoiceCardName: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.textColor,
    fontFamily: fonts.neueHaasBold,
    marginBottom: 4,
  },
  invoiceCardContact: {
    fontSize: 14,
    color: '#666666',
    fontFamily: fonts.neueHaasRoman,
  },
  invoiceCardRight: {
    alignItems: 'flex-end',
    gap: 8,
  },
  invoiceCardActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  invoiceCardIconBtn: {
    padding: 4,
  },
  invoicePaidBadge: {
    backgroundColor: '#209688',
    paddingHorizontal: 14,
    paddingVertical: 4,
    borderRadius: 999,
    minWidth: 56,
    alignItems: 'center',
  },
  invoicePaidBadgeText: {
    color: colors.whiteColor,
    fontSize: 12,
    fontWeight: '700',
    fontFamily: fonts.neueHaasBold,
  },
  invoiceCardDivider: {
    height: 1,
    backgroundColor: '#E0E0E0',
  },
  invoiceCardSummary: {
    flexDirection: 'row',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 8,
    backgroundColor: colors.belowGrey,
    justifyContent: 'space-between',
  },
  invoiceCardSummaryCol: {
    flex: 1,
    minWidth: 0,
  },
  invoiceCardSummaryLabel: {
    fontSize: 12,
    color: '#666666',
    fontFamily: fonts.neueHaasRoman,
    marginBottom: 4,
  },
  invoiceCardSummaryValue: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textColor,
    fontFamily: fonts.neueHaasBold,
  },
  fab: {
    position: 'absolute',
    right: 16,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#E53935',
    alignItems: 'center',
    justifyContent: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
      },
      android: { elevation: 4 },
      default: {},
    }),
  },
  invoiceMenuRoot: {
    flex: 1,
  },
  invoiceMenuBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
  },
  invoiceMenuPopover: {
    position: 'absolute',
    backgroundColor: colors.whiteColor,
    borderRadius: 10,
    paddingVertical: 4,
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
      },
      android: { elevation: 6 },
      default: {},
    }),
  },
  invoiceMenuRow: {
    position: 'relative',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  invoiceMenuRowText: {
    fontSize: 15,
    color: colors.textColor,
    fontFamily: fonts.neueHaasRoman,
  },
  invoiceMenuRowDivider: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: 0,
    height: StyleSheet.hairlineWidth,
    backgroundColor: '#E0E0E0',
  },
});